### ISSUE TITLE
[Bugs] Several Issues With Telescope...

### ISSUE THREAD

**Issue by ahmedkhalf** [glepnir/dashboard-nvim#65]
Hello, I am experiencing several issues with telescope and I am not sure if the problem is from dashboard or telescope itself.

1. number and sign column are not visible after using telescope:
    Steps to reproduce:
    1. `set number` and `set signcolumn=yes` in init.vim
    2. select a a recently opened file from dashboard-nvim
    3. to your horror, when the file is open, it does not have a number and sign column

2. Pressing escape when telescope is on creates an empty buffer and closes dashboard-nvim
    Expected behavior: Pressing escape should return me to the dashboard-nvim and not creates an empty buffer...

3. Pressing ctrl-j & ctrl-k does not bring my cursor up or down in telescope but instead write the ctrl character in the text box.

**Comment by ahmedkhalf** [comment]
I have successfully identified why 1 and 2 are happening: terminal size?!
When my terminal occupies half the screen, bug 1 and 2 appear, but when terminal covers my full screen, bug 1 and 2 are gone...

**Comment by ChristianChiarulli** [comment]
@ahmedkhalf I think it is definitely due to the empty buffer created by telescope, hence why `nobuflisted` had an effect on the issue.

**Comment by glepnir** [comment]
with telescope right?

**Comment by glepnir** [comment]
check there https://github.com/nvim-telescope/telescope.nvim/issues/377

**Comment by glepnir** [comment]
it's an known issue of telescope . when you reduce the window size you will see this issue.

**Comment by ronisbr** [comment]
I just found an "acceptable" workaround until Telescope fix the issue. Add to your telescope configuration:

```
    layout_defaults = {
      flex = {
        flip_columns = 130
      }
    },
    layout_strategy = 'flex',
```

Hence, if the window is narrow, then the preview will be shown on top. If the preview window is shown, then this bug does not happen.

**Comment by akinsho** [comment]
Just adding this to help the debugging efforts.

I don't think this issue is entirely about telescope. Although I'm new to the party and could be wrong. I just started using this plugin and noticed my settings were being removed so I used `verbose set <affected-setting>?` for example `verbose set signcolumn?` just after opening a buffer with `telescope` coming from dashboard.

The output of that is 
```
signcolumn=auto
        Last set from ~/.local/share/nvim/site/pack/packer/start/dashboard-nvim/autoload/dashboard.vim line 40
```
[this line here](https://github.com/glepnir/dashboard-nvim/blob/181ca6577101c04dd220b7a25096cbd4325979ec/autoload/dashboard.vim#L40) sets a bunch of local setting like `signcolumn=no`, `nonumber norelativenumber` etc. The problem with this is that telescope at least not sure if any other picker does this re-uses the same window when it opens the selection, so all the window options remain the same. If I open a new window it uses the settings from my init.lua instead so the problem goes away.

I think not being super hot on vimscript that the values of the user's options should be saved before setting dashboard's settings and then on close of dashboard via an autocommand maybe the original user settings should be re-applied.

I know this function I pointed at is essentially the same as in startify but it also has the same problem i.e. if you open a buffer from telescope from startify init.lua setting don't get applied to the window.

**Comment by glepnir** [comment]
hmm does this issue still exist?

**Comment by ronisbr** [comment]
@glepnir Welcome back!!

**Comment by glepnir** [comment]
hello :)
